name: Setup CI environment
runs:
  using: composite
  steps:
    - name: Install Nix
      shell: bash
      run:
        curl --proto '=https' --tlsv1.2 -sSf -L https://install.lix.systems/lix
        | sh -s -- install --no-confirm
