# aws-greengrass-lite - AWS IoT Greengrass runtime for constrained devices
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
---
RecipeFormatVersion: "2020-01-25"
ComponentName: "aws.greengrass.CloudLogger"
ComponentVersion: "1.0.0"
ComponentDescription: AWS Greengrass Cloud Logger
ComponentPublisher: AWS
Manifests:
  - Platform:
      os: linux
    Lifecycle:
      run: |
        {artifacts:path}/cloud-logger
