---
system:
  privateKeyPath: "/Users/sdarahas/Desktop/src/dev/aws-greengrass-lite/device.key"
  certificateFilePath: "/Users/sdarahas/Desktop/src/dev/aws-greengrass-lite/device.pem"
  rootCaPath: "..."
  rootpath: "."
  thingName: "GGC-test"
services:
  aws.greengrass.Nucleus-Lite:
    componentType: "NUCLEUS"
    configuration:
      awsRegion: "us-west-2"
      componentStoreMaxSizeBytes: "10000000000"
      deploymentPollingFrequencySeconds: "15"
      envStage: "prod"
      fleetStatus:
        periodicStatusPublishIntervalSeconds: 86400
      greengrassDataPlanePort: "8443"
      httpClient: {}
      iotCredEndpoint: "a3w4eclq1cog1t-ats.iot.us-east-2.amazonaws.com"
      iotDataEndpoint: "..."
      iotRoleAlias: "GreengrassV2TokenExchangeRoleAlias"
      logging:
        level: "DEBUG"
      mqtt:
        spooler: {}
      networkProxy:
        proxy: {}
      platformOverride: {}
      runWithDefault:
        posixUser: "ggc_user:ggc_group"
      telemetry: {}
    dependencies: []
  DeploymentService:
    dependencies: []
    version: "0.0.0"
  FleetStatusService:
    dependencies: []
    version: "0.0.0"
  main:
    dependencies:
      - "aws.greengrass.Nucleus-Lite"
    lifecycle: {}
  TelemetryAgent:
    dependencies: []
    version: "0.0.0"
  UpdateSystemPolicyService:
    dependencies: []
    version: "0.0.0"
