---
system:
  privateKeyPath: "/home/parallels/Documents/cert/ggtest/06e30fcd74acc4c143d69676439f57a40f4adcbd6d8abaf890e21f851650b734-private.pem.key"
  certificateFilePath: "/home/parallels/Documents/cert/ggtest/06e30fcd74acc4c143d69676439f57a40f4adcbd6d8abaf890e21f851650b734-certificate.pem.crt"
  rootCaPath: "/home/parallels/Documents/cert/ggtest/AmazonRootCA1.pem"
  rootpath: "."
  thingName: "GGC-test"
services:
  aws.greengrass.Nucleus-Lite:
    componentType: "NUCLEUS"
    configuration:
      awsRegion: "us-west-2"
      componentStoreMaxSizeBytes: "10000000000"
      deploymentPollingFrequencySeconds: "15"
      envStage: "prod"
      fleetStatus:
        periodicStatusPublishIntervalSeconds: 86400
      greengrassDataPlanePort: "8443"
      httpClient: {}
      iotCredEndpoint: "..."
      iotDataEndpoint: "a3w4eclq1cog1t-ats.iot.us-west-2.amazonaws.com"
      iotRoleAlias: "GreengrassV2TokenExchangeRoleAlias"
      logging:
        level: "DEBUG"
      mqtt:
        spooler: {}
      networkProxy:
        proxy: {}
      platformOverride: {}
      runWithDefault:
        posixUser: "ggc_user:ggc_group"
      telemetry: {}
    dependencies: []
  aws.greengrass.FleetProvisioningByClaim:
    configuration:
      iotDataEndpoint: "..."
      iotCredEndpoint: ""
      claimKeyPath: "..."
      claimCertPath: "..."
      deviceId: ""
      templateName: "..."
      templateParams: "..."
      csrPath: ""
      mqttPort: 80
      proxyUrl: ""
      proxyUsername: ""
      proxyPassword: ""
  DeploymentService:
    dependencies: []
    version: "0.0.0"
  FleetStatusService:
    dependencies: []
    version: "0.0.0"
  main:
    dependencies:
      - "aws.greengrass.Nucleus-Lite"
    lifecycle: {}
  TelemetryAgent:
    dependencies: []
    version: "0.0.0"
  UpdateSystemPolicyService:
    dependencies: []
    version: "0.0.0"
