name: Build

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    timeout-minutes: 100
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Linux GCC
            os: ubuntu-latest
            package: default
          - name: Linux LLVM
            os: ubuntu-latest
            package: gglite-clang
          - name: MacOS
            os: macos-14
            package: default
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: "tree:0"
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Build
        run: nix build -L --log-lines 0 .#${{ matrix.package }}

  build-windows:
    name: Windows MinGW
    timeout-minutes: 100
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: "tree:0"
      - name: Configure
        shell: bash
        run: |
          cmake -B build -G "MinGW Makefiles" \
            -DCMAKE_C_COMPILER=gcc \
            -DCMAKE_CXX_COMPILER=g++ \
            -DCMAKE_BUILD_TYPE=Debug \
            -DBUILD_TESTING=1
      - name: Build
        run: make -C build -j4
      - name: Tests
        working-directory: ${{ github.workspace }}/build
        run: ctest -R nucleus --output-on-failure
