name: Build

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    timeout-minutes: 60
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-20.04, windows-latest, macos-latest]
        build_type: [Debug]
        compiler: [g++, clang++, msvc]
        exclude:
          - os: windows-latest
            compiler: clang++
          - os: ubuntu-20.04
            compiler: msvc
          - os: macos-latest
            compiler: g++
          - os: macos-latest
            compiler: msvc

    steps:
      - name: Clone the repo
        uses: actions/checkout@v3

      - name: Install dependencies
        if: matrix.os == 'windows-latest' && matrix.compiler == 'g++'
        run: >
          choco install mingw

      - name: Configure CMake
        run: >
          cmake -B ${{ github.workspace }}/build -DCMAKE_CXX_COMPILER=${{matrix.compiler}}
          -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -S ${{github.workspace}}

      - name: Build
        run:
          cmake --build ${{ github.workspace }}/build --config
          ${{ matrix.build_type }}

      - name: Run Tests
        working-directory: ${{ github.workspace }}/build
        run: ./nucleus/nucleus-tests -d yes
