name: Test

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    timeout-minutes: 100
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-20.04
            c_compiler: gcc
            cpp_compiler: g++
            build_type: Debug
          - os: ubuntu-20.04
            c_compiler: clang
            cpp_compiler: clang++
            build_type: Debug
          - os: macos-latest
            c_compiler: clang
            cpp_compiler: clang++
            build_type: Debug
    runs-on: ${{ matrix.os }}
    steps:
      - name: Clone the repo
        uses: actions/checkout@v4

      - name: Configure CMake
        shell: bash
        run: |
          cmake -B build -S . \
            -DCMAKE_C_COMPILER=${{matrix.c_compiler}} \
            -DCMAKE_CXX_COMPILER=${{matrix.cpp_compiler}} \
            -DCMAKE_BUILD_TYPE=${{matrix.build_type}} \
            -DBUILD_TESTING=1

      - name: Build
        run:
          cmake --build ${{ github.workspace }}/build --config ${{
          matrix.build_type }} -j4

      - name: Run Tests
        working-directory: ${{ github.workspace }}/build
        run: ctest -R nucleus --output-on-failure

  build-windows:
    name: Windows MinGW
    timeout-minutes: 100
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: "tree:0"
      - name: Configure
        shell: bash
        run: |
          cmake -B build -G "MinGW Makefiles" \
            -DCMAKE_C_COMPILER=gcc \
            -DCMAKE_CXX_COMPILER=g++ \
            -DCMAKE_BUILD_TYPE=Debug \
            -DBUILD_TESTING=1
      - name: Build
        run: make -C build -j4
      - name: Tests
        working-directory: ${{ github.workspace }}/build
        run: ctest -R nucleus --output-on-failure
