name: Linting / Formatting

on:
  workflow_call:
  workflow_dispatch:

jobs:
  format-check:
    name: Check Formatting
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Check Formatting
        id: formatting-check
        run: nix build -L .#checks.x86_64-linux.formatting

      - name: Generate / Show Patch
        if: ${{ failure() && steps.formatting-check.outcome == 'failure' }}
        shell: nix develop -c bash -exo pipefail {0}
        run: |
          nix fmt
          git diff >> formatting.patch
          git diff --color=always

      - name: Upload Patch
        if: ${{ failure() && steps.formatting-check.outcome == 'failure' }}
        uses: actions/upload-artifact@v3
        with:
          name: formatting_patch
          path: formatting.patch
          retention-days: 5

  clang-tidy:
    name: Check Clang-tidy
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: nix develop -c bash -exo pipefail {0}
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Configure project
        run: cmake $cmakeFlags -B build

      - name: Check Clang-tidy
        id: clang-tidy-check
        run: |
          clang-tidy -p ./build --warnings-as-errors='*' -header-filter=.* \
            $(fd -t f -e cpp)

      - name: Generate / Show Patch
        if: ${{ failure() && steps.clang-tidy-check.outcome == 'failure' }}
        run: |
          clang-tidy -p ./build -header-filter=.* --fix --fix-errors --quiet \
            $(fd -t f -e cpp)
          git diff >> clang-tidy.patch
          git diff --color=always

      - name: Upload Patch
        if: ${{ failure() && steps.clang-tidy-check.outcome == 'failure' }}
        uses: actions/upload-artifact@v3
        with:
          name: clang-tidy_patch
          path: clang-tidy.patch
          retention-days: 5

  cppcheck:
    name: Check cppcheck
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: nix develop -c bash -exo pipefail {0}
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Configure project
        run: cmake $cmakeFlags -B build

      - name: Check cppcheck
        id: cppcheck-run
        run: |
          mkdir .cppcheck
          cppcheck_flags="--cppcheck-build-dir=.cppcheck --quiet --std=c++17 \
            --project=build/compile_commands.json -ibuild -inucleus/tests \
            --check-level=exhaustive --enable=all --inconclusive --verbose \
            --suppress=missingIncludeSystem --suppress=*:build/* \
            --inline-suppr"
          # print output, save to text file, and save to xml (only checks once)
          cppcheck $cppcheck_flags
          cppcheck $cppcheck_flags 2> report.txt
          cppcheck $cppcheck_flags --xml 2> report.xml
          [ ! -s report.txt ] || exit 1

      - name: Generate report
        if: ${{ failure() && steps.cppcheck-run.outcome == 'failure' }}
        run: cppcheck-htmlreport --file=report.xml --report-dir=cppcheck_report

      - name: Upload report
        if: ${{ failure() && steps.cppcheck-run.outcome == 'failure' }}
        uses: actions/upload-artifact@v3
        with:
          name: cppcheck_report
          path: cppcheck_report
          retention-days: 5

  editorconfig:
    name: Check editorconfig-checker
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Check editorconfig-checker
        run: nix build -L .#checks.x86_64-linux.editorconfig

  cmake-lint:
    name: Check CMake
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Check CMake
        run: nix build -L .#checks.x86_64-linux.cmake-lint

  git-secrets:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Run git-secrets
        shell: nix develop -c bash -eo pipefail {0}
        run: |
          git-secrets --register-aws
          git-secrets --scan
