name: CI Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
  linting:
    uses: ./.github/workflows/lints.yml
